### ISSUE TITLE
iptables log forever growing

### ISSUE THREAD

**Issue by Strasedon** [tohojo/sqm-scripts#100]
The contents of /var/run/sqm/${IFACE}.iptables.log is appended to between restarts of the service. I had expected that it would be cleared/removed after a "service sqm stop" (presumably after ipt_log_rewind is finished).

**Comment by moeller0** [comment]
So, I just tested it, and yes, we do not delete that log on stop-sqm, true, but we do delete it in sqm_start_default, so it does not grow forever, assuming the user did not supply her/his own sqm_start() as part of the .qos-script. @tohojo how about we move the ipt_log_restart() call from sqm_start_default to start-sqm, just before calling sqm_start_default() or sqm_start() to assure that it was reset? Or follow @Strasedon 's proposal and delete it in sqm-stop/stop-sqm?

**Comment by tohojo** [comment]
Strasedon <notifications@github.com> writes:

> The contents of /var/run/sqm/${IFACE}.iptables.log is appended to
> between restarts of the service. I had expected that it would be
> cleared/removed after a "service sqm stop" (presumably after
> ipt_log_rewind is finished).

Heh, we literally just merged the pull request to fix this today. See
https://github.com/tohojo/sqm-scripts/commit/e699a6519ab78e9950d989f0311b2e8a009fc5c0

**Comment by moeller0** [comment]
Hi Toke,

I might be wrong, but I believe this issue is about the iptables unroll log and not our debug log.

**Comment by moeller0** [comment]
So I commited a quick fix, by calling ipt_log_restart() in sqm-stop immediately after calling ipt_log_rewind(), so basically the very moment the log becomes expendable. We can discuss other options, but for users supplying their own sqm-start() that seems like the right thing to do.

**Comment by moeller0** [comment]
@Strasedon could you test the current master again, and if I might ask, do you use your own qos script with an overriding sqm-start() function?

**Comment by moeller0** [comment]
Hi Strasedon,

> On Aug 26, 2019, at 21:37, Strasedon <notifications@github.com> wrote:
> 
> Correct, and the script I'm using does provide a sqm_start function.

	Which is just as it should be, being able to override/supply your own sqm_start() is part of sqm-scripts design. I was simply an oversight during testing, that I did not test, nor consider this case at all.

> However, it does nothing different from the one it is based on (layer_cake.qos) so I can remove sqm_start and provide the same sqm_prepare_script function as the one in the repo.

	That is a good idea, but should be orthogonal to the real issue, which should be fixed now, not necessarily in the best way (so the solution might change).
