### ISSUE TITLE
iptables transaction log doesn't support comments

### ISSUE THREAD

**Issue by Strasedon** [tohojo/sqm-scripts#101]
As it stands now, a rule invoked like:

` ipt -t mangle -A QOS_MARK_${IFACE} -m set --match-set bulkset dst -m comment --comment "Set DSCP for bulk traffic" -j DSCP --set-dscp-class CS1`

Will produce a line in the log like:

`-t mangle -D QOS_MARK_eth0.2 -m set --match-set bulkset dst -m comment --comment Set DSCP for bulk traffic -j DSCP --set-dscp-class CS1`

To minimize my odds of breaking things, I tried calling ipt_log with "$@" as the argument (need to keep the comment as one entry in the array) and changed it like so (pardon my horrible shell scripting):

```
ipt_log() {

        local output=""
        while [ $# -ne 0 ] ; do
                case $1 in
                        -A)
                                output="$output -D"
                                shift
                                ;;

                        -I)
                                output="$output -D"
                                shift
                                ;;
                        -N)
                                output="$output -X"
                                shift
                                ;;
                        --comment) output="$output --comment"
                                shift
                                output="$output \"$1\""
                                shift
                                ;;
                esac
                output="$output $1"
                shift
        done


    echo "$output" >> "$IPT_TRANS_LOG"
}
```

Which leaves the attempt to delete the rules in ipt broken, but that could be fixed later. The transaction log then contains:

`-t mangle -D QOS_MARK_eth0.2 -m set --match-set bulkset dst -m comment --comment "Set DSCP for bulk traffic" -j DSCP --set-dscp-class CS1`

Which looks good, but sqm-scripts still can't delete them. The debug log contains:

```
SQM: cmd_wrapper: iptables: invocation silenced by request, FAILURE either expected or acceptable.
SQM: cmd_wrapper: iptables: FAILURE (2): /usr/sbin/iptables -t mangle -D QOS_MARK_eth0.2 -m set --match-set bulkset dst -m comment --comment "Set DSCP for bulk traffic" -j DSCP --set-dscp-class CS1
SQM: cmd_wrapper: iptables: LAST ERROR: Bad argument `DSCP'
Try `iptables -h' or 'iptables --help' for more information.
```
Weird. I can copy and paste the command in that error message and it works fine, so maybe there is some command wrapper shenanigans going on and I am in way over my head at that point. Perhaps the command is being truncated?

Responses may be a bit slow, my nephew is having surgery today and I expect I'll be busy when he is home.

**Comment by moeller0** [comment]
Mmmh,

we never supported comments in iptables commands, but that actually seems useful to have, but I do we actually need to supply the comment itself for deleting a rule/chain, otherwise we could just filter these out in ipt_log and the space issue should be gone, alternatively we could try to put something similar to your code into ipt()? @Tohojo what do you think?

**Comment by tohojo** [comment]
moeller0 <notifications@github.com> writes:

> Mmmh,
>
> we never supported comments in iptables commands, but that actually
> seems useful to have, but I do we actually need to supply the comment
> itself for deleting a rule/chain, otherwise we could just filter these
> out in ipt_log and the space issue should be gone, alternatively we
> could try to put something similar to your code into ipt()? @Tohojo
> what do you think?

We should definitely fix the quoting so that this works; that was
actually one of the use cases I had in mind when I complained about the
lack of quoting earlier.

But yeah, probably needs a bit of work to handle the roll-back properly.
I'll take a look tomorrow...

**Comment by tohojo** [comment]
Right, after much experimentation with weird shell constructs, I think I got
something that works; please check if things work for you with commit 0b6ca5864d5d4db762823338408b1c9ac8338c27

**Comment by Strasedon** [comment]
It hangs on startup (not using comments yet).

```
root@OpenWrt:/tmp/run/sqm# service sqm start
SQM: Starting SQM script: layer_cake_dscp.qos on eth0.2, in: 6000 Kbps, out: 516 Kbps
SQM: fn_exists: function candidate name: sqm_start
SQM: fn_exists: TYPE_OUTPUT: sqm_start: not found
SQM: fn_exists: return value: 1
SQM: Using generic sqm_start_default function.
SQM: fn_exists: function candidate name: sqm_prepare_script
SQM: fn_exists: TYPE_OUTPUT: sqm_prepare_script is a function
SQM: fn_exists: return value: 0
SQM: sqm_start_default: starting sqm_prepare_script
SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link add name TMP_IFB_4_SQM type ifb
SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc qdisc replace dev TMP_IFB_4_SQM root cake
SQM: QDISC cake is useable.
SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link set dev TMP_IFB_4_SQM down
SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link delete TMP_IFB_4_SQM type ifb
SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link add name TMP_IFB_4_SQM type ifb
SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc qdisc replace dev TMP_IFB_4_SQM root cake
SQM: QDISC cake is useable.
SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link set dev TMP_IFB_4_SQM down
SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link delete TMP_IFB_4_SQM type ifb
SQM: sqm_start_default: Starting layer_cake_dscp.qos
SQM: ifb associated with interface eth0.2: ifb4eth0.2
SQM: fn_exists: function candidate name: egress
SQM: fn_exists: TYPE_OUTPUT: egress is a function
SQM: fn_exists: return value: 0
SQM: cmd_wrapper: tc: invocation silenced by request, FAILURE either expected or acceptable.
SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc qdisc del dev eth0.2 root
SQM: LLA: default link layer adjustment method for cake is cake
SQM: cake link layer adjustments: atm overhead 32 mpu 0
SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc qdisc add dev eth0.2 root handle cacf: cake bandwidth 516kbit atm overhead 32 mpu 0 diffserv3 nat dual-srchost mpu 64 ack-filter diffserv4
SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc filter add dev eth0.2 protocol all prio 10 u32 match u32 0 0 flowid 1:1 action ctinfo dscp 0xfc000000 0x01000000
SQM: sqm_start_default: egress shaping activated
SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link add name TMP_IFB_4_SQM type ifb
SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc qdisc replace dev TMP_IFB_4_SQM ingress
SQM: QDISC ingress is useable.
SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link set dev TMP_IFB_4_SQM down
SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link delete TMP_IFB_4_SQM type ifb
SQM: fn_exists: function candidate name: ingress
SQM: fn_exists: TYPE_OUTPUT: ingress is a function
SQM: fn_exists: return value: 0
SQM: cmd_wrapper: tc: invocation silenced by request, FAILURE either expected or acceptable.
SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc qdisc del dev eth0.2 handle ffff: ingress
SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc qdisc add dev eth0.2 handle ffff: ingress
SQM: cmd_wrapper: tc: invocation silenced by request, FAILURE either expected or acceptable.
SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc qdisc del dev ifb4eth0.2 root
SQM: LLA: default link layer adjustment method for cake is cake
SQM: cake link layer adjustments: atm overhead 32 mpu 0
SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc qdisc add dev ifb4eth0.2 root handle cace: cake bandwidth 6000kbit atm overhead 32 mpu 0 diffserv3 besteffort wash nat dual-dsthost mpu 64 ingress diffserv4
SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link set dev ifb4eth0.2 up
SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc filter add dev eth0.2 parent ffff: protocol all prio 10 u32 match u32 0 0 flowid 1:1 action ctinfo dscp 0xfc000000 0x01000000 mirred egress redirect dev ifb4eth0.2
^C
```
And when stopping:

```
root@OpenWrt:/tmp/run/sqm# service sqm stop
/usr/lib/sqm/run.sh: line 101: sqm_warning: not found
/usr/lib/sqm/run.sh: line 101: sqm_warning: not found
/usr/lib/sqm/run.sh: line 101: sqm_warning: not found
/usr/lib/sqm/run.sh: line 101: sqm_warning: not found
/usr/lib/sqm/run.sh: line 101: sqm_warning: not found
/usr/lib/sqm/run.sh: line 101: sqm_warning: not found
/usr/lib/sqm/run.sh: line 101: sqm_warning: not found
/usr/lib/sqm/run.sh: line 101: sqm_warning: not found
/usr/lib/sqm/run.sh: line 101: sqm_warning: not found
/usr/lib/sqm/run.sh: line 101: sqm_warning: not found
SQM: ERROR: Giving up on getting lock after 10 attempts
SQM: ERROR: This is a bug; please report it at https://github.com/tohojo/sqm-scripts/issues
SQM: ERROR: Then, to re-enable sqm-scripts, manually remove /var/run/sqm/sqm-run.lock
Command failed: Not found
```

One thing I caught is that in ipt_negate I think you meant to have "-X" in the case for "-N".

I've attached my qos script for reference.
[layer_cake_dscp.qos.txt](https://github.com/tohojo/sqm-scripts/files/3555542/layer_cake_dscp.qos.txt)

**Comment by tohojo** [comment]
Strasedon <notifications@github.com> writes:

> It hangs on startup (not using comments yet).
>
> ```
> root@OpenWrt:/tmp/run/sqm# service sqm start
> SQM: Starting SQM script: layer_cake_dscp.qos on eth0.2, in: 6000 Kbps, out: 516 Kbps
> SQM: fn_exists: function candidate name: sqm_start
> SQM: fn_exists: TYPE_OUTPUT: sqm_start: not found
> SQM: fn_exists: return value: 1
> SQM: Using generic sqm_start_default function.
> SQM: fn_exists: function candidate name: sqm_prepare_script
> SQM: fn_exists: TYPE_OUTPUT: sqm_prepare_script is a function
> SQM: fn_exists: return value: 0
> SQM: sqm_start_default: starting sqm_prepare_script
> SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link add name TMP_IFB_4_SQM type ifb
> SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc qdisc replace dev TMP_IFB_4_SQM root cake
> SQM: QDISC cake is useable.
> SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link set dev TMP_IFB_4_SQM down
> SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link delete TMP_IFB_4_SQM type ifb
> SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link add name TMP_IFB_4_SQM type ifb
> SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc qdisc replace dev TMP_IFB_4_SQM root cake
> SQM: QDISC cake is useable.
> SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link set dev TMP_IFB_4_SQM down
> SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link delete TMP_IFB_4_SQM type ifb
> SQM: sqm_start_default: Starting layer_cake_dscp.qos
> SQM: ifb associated with interface eth0.2: ifb4eth0.2
> SQM: fn_exists: function candidate name: egress
> SQM: fn_exists: TYPE_OUTPUT: egress is a function
> SQM: fn_exists: return value: 0
> SQM: cmd_wrapper: tc: invocation silenced by request, FAILURE either expected or acceptable.
> SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc qdisc del dev eth0.2 root
> SQM: LLA: default link layer adjustment method for cake is cake
> SQM: cake link layer adjustments: atm overhead 32 mpu 0
> SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc qdisc add dev eth0.2 root handle cacf: cake bandwidth 516kbit atm overhead 32 mpu 0 diffserv3 nat dual-srchost mpu 64 ack-filter diffserv4
> SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc filter add dev eth0.2 protocol all prio 10 u32 match u32 0 0 flowid 1:1 action ctinfo dscp 0xfc000000 0x01000000
> SQM: sqm_start_default: egress shaping activated
> SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link add name TMP_IFB_4_SQM type ifb
> SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc qdisc replace dev TMP_IFB_4_SQM ingress
> SQM: QDISC ingress is useable.
> SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link set dev TMP_IFB_4_SQM down
> SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link delete TMP_IFB_4_SQM type ifb
> SQM: fn_exists: function candidate name: ingress
> SQM: fn_exists: TYPE_OUTPUT: ingress is a function
> SQM: fn_exists: return value: 0
> SQM: cmd_wrapper: tc: invocation silenced by request, FAILURE either expected or acceptable.
> SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc qdisc del dev eth0.2 handle ffff: ingress
> SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc qdisc add dev eth0.2 handle ffff: ingress
> SQM: cmd_wrapper: tc: invocation silenced by request, FAILURE either expected or acceptable.
> SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc qdisc del dev ifb4eth0.2 root
> SQM: LLA: default link layer adjustment method for cake is cake
> SQM: cake link layer adjustments: atm overhead 32 mpu 0
> SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc qdisc add dev ifb4eth0.2 root handle cace: cake bandwidth 6000kbit atm overhead 32 mpu 0 diffserv3 besteffort wash nat dual-dsthost mpu 64 ingress diffserv4
> SQM: cmd_wrapper: ip: SUCCESS: /sbin/ip link set dev ifb4eth0.2 up
> SQM: cmd_wrapper: tc: SUCCESS: /usr/sbin/tc filter add dev eth0.2 parent ffff: protocol all prio 10 u32 match u32 0 0 flowid 1:1 action ctinfo dscp 0xfc000000 0x01000000 mirred egress redirect dev ifb4eth0.2
> ^C
> ```
> And when stopping:
>
> ```
> root@OpenWrt:/tmp/run/sqm# service sqm stop
> /usr/lib/sqm/run.sh: line 101: sqm_warning: not found
> /usr/lib/sqm/run.sh: line 101: sqm_warning: not found
> /usr/lib/sqm/run.sh: line 101: sqm_warning: not found
> /usr/lib/sqm/run.sh: line 101: sqm_warning: not found
> /usr/lib/sqm/run.sh: line 101: sqm_warning: not found
> /usr/lib/sqm/run.sh: line 101: sqm_warning: not found
> /usr/lib/sqm/run.sh: line 101: sqm_warning: not found
> /usr/lib/sqm/run.sh: line 101: sqm_warning: not found
> /usr/lib/sqm/run.sh: line 101: sqm_warning: not found
> /usr/lib/sqm/run.sh: line 101: sqm_warning: not found
> SQM: ERROR: Giving up on getting lock after 10 attempts
> SQM: ERROR: This is a bug; please report it at https://github.com/tohojo/sqm-scripts/issues
> SQM: ERROR: Then, to re-enable sqm-scripts, manually remove /var/run/sqm/sqm-run.lock
> Command failed: Not found
> ```
>
> One thing I caught is that in ipt_negate I think you meant to have "-X" in the case for "-N".
>
> I've attached my qos script for reference.
> [layer_cake_dscp.qos.txt](https://github.com/tohojo/sqm-scripts/files/3555542/layer_cake_dscp.qos.txt)
>
>
>
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/tohojo/sqm-scripts/issues/101#issuecomment-526166323

Right, I think the latest two commits should fix both of those errors... :)

**Comment by Strasedon** [comment]
Seems to work fine now.  Thanks.

**Comment by tohojo** [comment]
Strasedon <notifications@github.com> writes:

> Seems to work fine now.  Thanks.

Awesome! Thanks for testing!
