### ISSUE TITLE
/usr/lib/sqm/functions.sh: line 84: type: sqm_start: not found

### ISSUE THREAD

**Issue by yutayu** [tohojo/sqm-scripts#102]
Is not it bug?

[ippan@ippan-pc sqm]$ sudo sqm reload
Starting SQM on all configured interfaces.
Starting SQM script: layer_cake.qos on eno1, in: 10600 Kbps, out: 795 Kbps
/usr/lib/sqm/functions.sh: line 84: type: sqm_start: not found
Using generic sqm_start_default function.
layer_cake.qos was started on eno1 successfully

**Comment by moeller0** [comment]
Not a bug, just a diagnostic message that the qos script did not supply its own over-ride sqm_start() function, so sqm used sqm_start_default() instead.

**Comment by tohojo** [comment]
It does sound a little like it could be a bug, though, maybe we should reword it...

**Comment by moeller0** [comment]
Fair enough, I will look at it later (unless someone beats me to it) work keeps me busy right now.

**Comment by yutayu** [comment]
I got it thanks :-)
