### ISSUE TITLE
SQM_STATE_DIR may be a temporary filesystem

### ISSUE THREAD

**Issue by taggart** [tohojo/sqm-scripts#104]
On many linux systems, the /run/ directory may exist on a temporary filesystem, so rather than have the [Makefile install it](https://github.com/tohojo/sqm-scripts/blob/master/Makefile#L30) it should be checked for and created if needed at runtime. It [looks like check_state_dir in functions.sh](https://github.com/tohojo/sqm-scripts/blob/master/src/functions.sh#L268)  already does the right thing. I don't think it hurts that 'make install' creates it, but Debian's lintian tool complains about it if it's included in the package. So consider dropping that line from the Makefile.

**Comment by tohojo** [comment]
taggart <notifications@github.com> writes:

> On many linux systems, the /run/ directory may exist on a temporary filesystem, so rather than have the [Makefile install it](https://github.com/tohojo/sqm-scripts/blob/master/Makefile#L30) it should be checked for and created if needed at runtime. It [looks like check_state_dir in functions.sh](https://github.com/tohojo/sqm-scripts/blob/master/src/functions.sh#L268)  already does the right thing. I don't think it hurts that 'make install' creates it, but Debian's lintian tool complains about it if it's included in the package. So consider dropping that line from the Makefile.

Sure, no objection to dropping it...
