### ISSUE TITLE
systemd unit files in /lib/systemd/system/ now

### ISSUE THREAD

**Issue by taggart** [tohojo/sqm-scripts#105]
It seems both Debian and Fedora are putting systemd unit files in /lib/systemd/system/ now. I think Fedora (at least) put them in /usr/lib/systemd/system/ for a while, but not anymore it seems. I don't know if there are distros still expecting the /usr/lib path, but I suspect it's safe to change the default install path in the Makefile.

**Comment by tohojo** [comment]
taggart <notifications@github.com> writes:

> It seems both Debian and Fedora are putting systemd unit files in
> /lib/systemd/system/ now. I think Fedora (at least) put them in
> /usr/lib/systemd/system/ for a while, but not anymore it seems. I
> don't know if there are distros still expecting the /usr/lib path, but
> I suspect it's safe to change the default install path in the
> Makefile.

Arch still uses /usr/lib - but it symlinks /lib to /usr/lib, so
installing into /lib won't actually break anything even on Arch. So I'm
fine with changing the default :)

**Comment by tohojo** [comment]
Hmm, actually it seems both Debian and Fedora are using the same symlink
from /lib to /usr/lib - so why do we need to change anything?

**Comment by taggart** [comment]
Existing installs and installs without "usrmerge" will still have them separate. Here's some documentation on Debian's [usrmerge](https://wiki.debian.org/UsrMerge)

But I just learned of a better way to do this with pkg-config: use the `systemdsystemunitdir` variable from the distro's systemd provided `/usr/share/pkgconfig/systemd.pc` file.

**Comment by tohojo** [comment]
taggart <notifications@github.com> writes:

> Existing installs and installs without "usrmerge" will still have them
> separate. Here's some documentation on Debian's
> [usrmerge](https://wiki.debian.org/UsrMerge)
>
> But I just learned of a better way to do this with pkg-config: use the
> `systemdsystemunitdir` variable from the distro's systemd provided
> `/usr/share/pkgconfig/systemd.pc` file.

Right, no objections to asking pkg-config, if it exists...
