### ISSUE TITLE
qos scripts executable?

### ISSUE THREAD

**Issue by taggart** [tohojo/sqm-scripts#106]
First this issue is very minor...

Debian's lintian tool is complaining that the /usr/lib/sqm/*.qos scripts should be executable since they start with the shebang line. I see that in start-sqm/stop-sqm they both source the qos with:
`. "${SQM_LIB_DIR}/$SCRIPT"`
which would work even without the shebang line. Are the qos scripts ever run by themselves? Maybe removing the shebang lines is the right answer here? If not then I guess the Makefile install-lib target could be changed to install just the qos files 0755.

**Comment by tohojo** [comment]
taggart <notifications@github.com> writes:

> First this issue is very minor...
>
> Debian's lintian tool is complaining that the /usr/lib/sqm/*.qos scripts should be executable since they start with the shebang line. I see that in start-sqm/stop-sqm they both source the qos with:
> `. "${SQM_LIB_DIR}/$SCRIPT"`
> which would work even without the shebang line. Are the qos scripts ever run by themselves? Maybe removing the shebang lines is the right answer here? If not then I guess the Makefile install-lib target could be changed to install just the qos files 0755.

No, executing the .qos files standalone doesn't work; we should just get
rid of the shebang...
