### ISSUE TITLE
Consider making piece_of_cake default

### ISSUE THREAD

**Issue by taggart** [tohojo/sqm-scripts#112]
Is it time for piece_of_cake to become the default linux distro SCRIPT in `platform/linux/default.conf`?

What about for openwrt in `platform/openwrt/sqm-uci`?

If so, what things need to be considered/tested before doing so? (I'm thinking upgrade path for existing installs, etc)

**Comment by tohojo** [comment]
taggart <notifications@github.com> writes:

> Is it time for piece_of_cake to become the default linux distro SCRIPT
> in `platform/linux/default.conf`?
>
> What about for openwrt in `platform/openwrt/sqm-uci`?

Sure, why not (for both)? :)

> If so, what things need to be considered/tested before doing so? (I'm
> thinking upgrade path for existing installs, etc)

Not sure we need to do anything much here? For packaged versions, there
should be distro tools that take care of any changes to config files.
For people doing a manual 'make install', we could use 'install -Cb' to
make sure we don't clobber any existing configs...
