### ISSUE TITLE
Add spec file to create RPM

### ISSUE THREAD

**Issue by SpareSimian** [tohojo/sqm-scripts#119]
Attached is what I'm using for CentOS 7. (.txt extension appended to allow upload here.)

[sqm-scripts.spec.txt](https://github.com/tohojo/sqm-scripts/files/4533337/sqm-scripts.spec.txt)

**Comment by tohojo** [comment]
Ah cool! I've been meaning to package it up for fedora. This is a nice starting point, thanks!

**Comment by SpareSimian** [comment]
The hard part is getting the SOURCE0 line right. I'd originally packaged with 1.3.0 and had the commented-out line for that piece, but it doesn't seem to work now. The tarball ends up having the wrong subdirectory with the wrong shortcommit tag in the directory name. So I switched to using the GitHub release link, instead.

You can use this command from the rpmdevtools package to download whatever appears in the SOURCE0 line to your SOURCES directory:

spectool -g -R sqm-scripts.spec

**Comment by jorti** [comment]
Hi, just a heads up that I've created the sqm-scripts package in Fedora.

If there's interest, I can add it to EPEL, although I'm not sure if cake is in the CentOS 8 kernel.

**Comment by tohojo** [comment]
Juan Orti Alcaine <notifications@github.com> writes:

> Hi, just a heads up that I've created the sqm-scripts package in
> Fedora.

Ah, cool! Would you mind adding me as co-maintainer for that?

> If there's interest, I can add it to EPEL, although I'm not sure if
> cake is in the CentOS 8 kernel.

Hmm, seems we're not even building fq_codel for RHEL/Centos? I'll see
if I can't get that fixed, but for now I guess that means there's no
need to put sqm-scripts into EPEL...

**Comment by jorti** [comment]
> Ah, cool! Would you mind adding me as co-maintainer for that?

Sure. Please, tell me your FAS account name.

**Comment by tohojo** [comment]
Juan Orti Alcaine <notifications@github.com> writes:

>> Ah, cool! Would you mind adding me as co-maintainer for that?
>
> Sure. Please, tell me your FAS account name.

Same as on github: tohojo

**Comment by jorti** [comment]
Ok done.

**Comment by SpareSimian** [comment]
fq_codel is the default qdisc in RHEL/CentOS 7. Try "cat /proc/sys/net/core/default_qdisc".

**Comment by tohojo** [comment]
Juan Orti Alcaine <notifications@github.com> writes:

> Ok done.

Great, thanks! The spec file LGTM :)

**Comment by tohojo** [comment]
SpareSimian <notifications@github.com> writes:

> fq_codel is the default qdisc in RHEL/CentOS 7. Try "cat
> /proc/sys/net/core/default_qdisc".

Yeah, I was looking for the module file and couldn't find it, but it
seems that this is because it's compiled as a kernel built-in not
because it's not there... My bad :)

So with that I guess we could push sqm-scripts to EPEL as well!

**Comment by SpareSimian** [comment]
There's been some discussion on the bufferbloat and cake mailing lists about compiling cake as a module but I don't have time to pursue it.

**Comment by tohojo** [comment]
SpareSimian <notifications@github.com> writes:

> There's been some discussion on the bufferbloat and cake mailing lists
> about compiling cake as a module but I don't have time to pursue it.

The out-of-tree version of cake compiles fine as a module; not sure if
it's possible to package kernel modules in EPEL, though...
