### ISSUE TITLE
sqm@.service startup failure when multiple instances are enabled

### ISSUE THREAD

**Issue by john-cameron-za** [tohojo/sqm-scripts#120]
When enabling sqm on more than one interface, the first instance starts OK at boot but
intermittently the rest could fail.

ERROR: cmd_wrapper: ip: FAILURE (2): /usr/sbin/ip link add name TMP_IFB_4_SQM type ifb
ERROR: cmd_wrapper: ip: LAST ERROR: RTNETLINK answers: File exists

Proposed fix is to unique the temp ifb interface so no overlap is possible with :

sed -i "s/TMP_IFB_4_SQM/\$( echo -n \"ifbtmp\${IFACE}\" | head -c 15 )/" /lib/sqm/functions.sh

**Comment by tohojo** [comment]
john-cameron-za <notifications@github.com> writes:

> When enabling sqm on more than one interface, the first instance starts OK at boot but
> intermittently the rest could fail.
>
> ERROR: cmd_wrapper: ip: FAILURE (2): /usr/sbin/ip link add name TMP_IFB_4_SQM type ifb
> ERROR: cmd_wrapper: ip: LAST ERROR: RTNETLINK answers: File exists
>
> Proposed fix is to unique the temp ifb interface so no overlap is possible with :
>
> sed -i "s/TMP_IFB_4_SQM/\$( echo -n \"ifbtmp\${IFACE}\" | head -c 15 )/" /lib/sqm/functions.sh

Oh yeah, I can see how that is going to break on parallel setup
attempts... let's just use a random name for that check.
