### ISSUE TITLE
diagram needed

### ISSUE THREAD

**Issue by taggart** [tohojo/sqm-scripts#125]
If would be helpful to have a example diagram of how sqm-scripts sets things up and why. For example it creates the ifb4 stuff to sit in front of devices, etc. A dia diagram or mermaid or something with labels and the lines from 'qdisc show' etc.

**Comment by tohojo** [comment]
taggart <notifications@github.com> writes:

> If would be helpful to have a example diagram of how sqm-scripts sets
> things up and why. For example it creates the ifb4 stuff to sit in
> front of devices, etc. A dia diagram or mermaid or something with
> labels and the lines from 'qdisc show' etc.

A diagram of what, exactly? Logically, we 'just' install a qdisc on
egress and one on ingress; it's just that the ingress one needs the ifb
device to work. So what should the diagram show, exactly? :)

**Comment by taggart** [comment]
Well it's not great, maybe something like this
![example](https://user-images.githubusercontent.com/476401/99479609-5ad1a580-290b-11eb-8a36-e8e0757431c2.png) Here's the dia file (gzip'd cause github)
[example.dia.gz](https://github.com/tohojo/sqm-scripts/files/5557551/example.dia.gz)

I was trying to wrap my head around why ifb4 existed and how it worked. Maybe it could somehow explain that qdisc's can only work on packets leaving a device and that's the reason for the ifb4.

**Comment by jonassmedegaard** [comment]
Very helpful!

Thanks, @taggart !
