### ISSUE TITLE
document iproute2 version requirements

### ISSUE THREAD

**Issue by taggart** [tohojo/sqm-scripts#126]
minor issue....
The readme should mention the iproute2 requirement and required version.
For example you didn't add cake support until iproute2 version 4.19

**Comment by tohojo** [comment]
taggart <notifications@github.com> writes:

> minor issue....
> The readme should mention the iproute2 requirement and required version.
> For example you didn't add cake support until iproute2 version 4.19

Well, actually what happened was that CAKE was included in upstream
Linux starting with v4.19. So before that you could still run it, but
you had to build it out-of-tree (including the iproute2 support).

I guess I can add a note with this to the README :)
