### ISSUE TITLE
iptables lock contention

### ISSUE THREAD

**Issue by SpareSimian** [tohojo/sqm-scripts#132]
I'm testing a new bloat test website and noticed I was getting a terrible bloat grade. When I looked at sqm-start log I discovered that a lot of the iptables commands had failed from failing to get an xlock. I stopped and started the systemd unit and re-ran the test and got an A+ bloat grade. The log showed no lock contention. I suspect that when the system boots the start script is competing with firewalld and fail2ban for the lock. The log has lines suggesting the use of the -w switch to wait for the lock.

I'm using the sqm-scripts-1.4.0-1.el7.noarch package from the EPEL repo.

Perhaps add an option to use the -w switch?

**Comment by tohojo** [comment]
SpareSimian <notifications@github.com> writes:

> I'm testing a new bloat test website and noticed I was getting a
> terrible bloat grade. When I looked at sqm-start log I discovered that
> a lot of the iptables commands had failed from failing to get an
> xlock. I stopped and started the systemd unit and re-ran the test and
> got an A+ bloat grade. The log showed no lock contention. I suspect
> that when the system boots the start script is competing with
> firewalld and fail2ban for the lock. The log has lines suggesting the
> use of the -w switch to wait for the lock.
>
> I'm using the sqm-scripts-1.4.0-1.el7.noarch package from the EPEL
> repo.

Which .qos script are you using?

> Perhaps add an option to use the -w switch?

Any reason not to just always use the switch?

**Comment by SpareSimian** [comment]
I'm using simple.qos.

I thought perhaps omitting the switch was an attempt to avoid a deadlock. It's not an issue with a systemd unit since those run in parallel.
