### ISSUE TITLE
Some modules not loaded (CentOS 7)

### ISSUE THREAD

**Issue by SpareSimian** [tohojo/sqm-scripts#133]
In my start-sqm.log I see three modules not getting loaded. They're available and I can modprobe them from the command line but not using insmod. The relevant log lines:

insmod: ERROR: could not load module act_ipt: No such file or directory
insmod: ERROR: could not load module cls_flow: No such file or directory
insmod: ERROR: could not load module sch_hfsc: No such file or directory

I get the same error using "insmod act_ipt". modprobe successfully installs that module. (I haven't tested the other two.)

uname -a shows:
Linux saruman.mpa.lan 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

sqm-scripts is sqm-scripts-1.4.0-1.el7.noarch from EPEL repo, patched to add the -w flag to iptables. I'm using simple.qos with fq_codel.

**Comment by SpareSimian** [comment]
I did read through issues #3 and #13 and I'm puzzled why insmod is getting selected, since modprobe is available.

**Comment by tohojo** [comment]
SpareSimian <notifications@github.com> writes:

> I did read through issues #3 and #13 and I'm puzzled why insmod is
> getting selected, since modprobe is available.

Well, defaults.sh does this:

[ -z "$INSMOD" ] && INSMOD=$(which modprobe) || INSMOD=$(which insmod)

so I suppose 'which modprobe' is failing? Maybe this is a PATH issue?

You can also override the setting in /etc/sqm/sqm.conf - just setting
the INSMOD variable should do the trick...

**Comment by SpareSimian** [comment]
I may overrride it. But I'm still wondering why it's not finding modprobe. Both insmod and modprobe are in /usr/sbin and are symlinks to /usr/bin/kmod.

I did throw a 'sqm_log "INSMOD=${INSMOD}"' in do_modules while debugging this last night and indeed saw it using /usr/sbin/insmod. I'll test the which output tonight when the system isn't in use.

**Comment by SpareSimian** [comment]
I see it now. This line always executes the last assignment no matter what. It's not acting like a fallback assignment as intended.

[ -z "$INSMOD" ] && INSMOD=$(which modprobe) || INSMOD=$(which insmod)

**Comment by tohojo** [comment]
What shell (and version) is it being run with?

**Comment by SpareSimian** [comment]
bash-4.2.46-34.el7.x86_64

I can run the line interactively and see it fail, choosing the fallback option. So you should be able to see this with any recent desktop distro. Or spin up a VPS at Linode to see it. 

I was looking at how this line is supposed to be interpreted and I think it's supposed to use the result of the which command as the status of the assignment, so it seems correct. So I'm puzzled why it's failing.

https://unix.stackexchange.com/questions/270828/how-is-the-return-status-of-a-variable-assignment-determined

**Comment by gordonmessmer** [comment]
[ -z "$INSMOD" ] && INSMOD=$(which modprobe) || INSMOD=$(which insmod)

This should be re-written as:

    [ -z "$INSMOD" ] && { INSMOD=$(which modprobe) || INSMOD=$(which insmod) ; }

As it is currently written, if INSMOD is set previously, it will be replaced with the output of "which insmod".  That is, the final statement will be evaluated if either INSMOD was set previously, or if "which modprobe" exits with a non-zero status.

It's unlikely that this is a PATH issue since both modprobe and insmod are in the same directory.  The most likely explanation is that $INSMOD had a value before that line was evaluated.

**Comment by tohojo** [comment]
Gordon Messmer <notifications@github.com> writes:

>     [ -z "$INSMOD" ] && INSMOD=$(which modprobe) || INSMOD=$(which insmod)
>
> This should be re-written as:
>
>     [ -z "$INSMOD" ] && { INSMOD=$(which modprobe) || INSMOD=$(which insmod) ; }
>
> As it is currently written, if INSMOD is set previously, it will be
> replaced with the output of "which insmod". That is, the final
> statement will be evaluated if either INSMOD was set previously, or if
> "which modprobe" exits with a non-zero status.
>
> It's unlikely that this is a PATH issue since both modprobe and insmod
> are in the same directory. The most likely explanation is that $INSMOD
> had a value before that line was evaluated.

Ah, bingo! 'start-sqm' includes defaults.sh, and simple.qos does as
well. So indeed it is evaluated twice. Nicely spotted! :)
