### ISSUE TITLE
SQM and VPN speed limited (bypass possible?)

### ISSUE THREAD

**Issue by falacu** [tohojo/sqm-scripts#151]
I have an openwrt 22.03 in a RP4 with smq enabled. Another  rp4 with a wireguard vpn is connected to the openwrt. 
When i connect to the vpn i have half limited the speed compared to sqm disabled (I have 100 Mbps down and up, and with sqm I can reach 50 up and down). I couldn't find where is the problem. I want to know if is it possible to bypass in any way the sqm. I think there is no problem with the CPU,  the load doest reach 15% with Speedtest and VPN connected. Thanks! And sorry for my bad English.

**Comment by tohojo** [comment]
If you're bypassing SQM for the VPN you won't get any benefit of it, so
you might as well turn it off.

As for why it affects throughput, that's hard to tell without more
details of your setup and which tests you're running to see this...

**Comment by falacu** [comment]
Thanks for your quickly answer. I leave a diagram of my network and configuration of SQM and Openwrt. I used speedtest.net to verify the connection.
 VPN Speed:
80/85 mbps up and down - SQM OFF
50 mbpsup and down - SQM ON

![red](https://user-images.githubusercontent.com/114259264/193154684-6a898fd4-e702-49a6-9771-1af162a7672c.jpg)
![red2](https://user-images.githubusercontent.com/114259264/193154674-6c9dabed-a8bd-4361-a28f-e264090bdace.jpg)
![red3](https://user-images.githubusercontent.com/114259264/193154676-8fde3d99-1ce8-4bec-8382-84809e7e7cdb.jpg)
![red4](https://user-images.githubusercontent.com/114259264/193154677-fccaf8e3-7cd9-4f3a-b507-023134801896.jpg)
![red5](https://user-images.githubusercontent.com/114259264/193154679-c391424f-8503-4ce9-88aa-680c661fdddd.jpg)
![red6](https://user-images.githubusercontent.com/114259264/193154682-b0cdbd12-6b2b-4857-bbbc-07df9461d957.jpg)

**Comment by tohojo** [comment]
And which devices are connected through the VPN? How are you running speedtest through the VPN?

**Comment by falacu** [comment]
When you  ask me for more details I understood it.
I was using the vpn from the same network, in that case the 2 peers are
downloading at the same time and that is why the sqm limits just in the
middle. I think that's the point. I am trying the vpn with sqm for the
first time and I had not realized this detail.
Connecting the client from the internet should not be a problem, I did the
test and it worked at 89 Mbps.
I apologize for the silly question and the waste of time.
Thank you very much

**Comment by tohojo** [comment]
Great! You're welcome! :)
