### ISSUE TITLE
Undeclared MTU variable

### ISSUE THREAD

**Issue by dave14305** [tohojo/sqm-scripts#172]
https://github.com/tohojo/sqm-scripts/blob/424184d55db476a3816426da3d1c0e4bae728798/src/functions.sh#L601

This MTU variable should be `HTB_MTU` to match the `local HTB_MTU` declaration.

**Comment by tohojo** [comment]
Nice catch! Care to open a PR with a fix? :)

**Comment by dave14305** [comment]
I would not be willing to comply with the SoB requirement, due to privacy. Hope you understand.

**Comment by tohojo** [comment]
dave14305 ***@***.***> writes:

> I would not be willing to comply with the SoB requirement, due to
> privacy. Hope you understand.

Fair, I'll add the fix :)

**Comment by dave14305** [comment]
Fixed with 95337de67a35b474d493966223f324eb1302adfc
