### ISSUE TITLE
Including the luci app in this repository?

### ISSUE THREAD

**Issue by tohojo** [tohojo/sqm-scripts#2]
Would it make sense to keep the Luci app in this repository as well? Might make it easier to keep things in sync, and we could still have separate packages in the openwrt repos...

**Comment by moeller0** [comment]
Hi Toke,

On Jul 29, 2015, at 15:04 , Toke H�iland-J�rgensen <notifications@github.com> wrote:

> Would it make sense to keep the Luci app in this repository as well? Might make it easier to keep things in sync, and we could still have separate packages in the openwrt repos�

	I am fine with moving it over; keeping it separate is not a big hassle, but synchronization is going to be easier. Though I have no planned major changes for the GUI queued up, the qdisc verification was the only issue I wanted to tackle�

Best Regards
	Sebastian
