### ISSUE TITLE
Evaluation of the available qdiscs: explanation in GUI is wrong

### ISSUE THREAD

**Issue by hnyman** [tohojo/sqm-scripts#20]
I tested yesterday building SQM with cake for Openwrt trunk, and while doing that I ran into two documentation / clarity issues. This is the first one of them.

I installed the cake kmod to the router and restarted sqm, but cake qdisc was still not available in SQM. It took me a while to figure out why, although SQM Luci GUI claims that a new browser session is enough ;-)
https://github.com/tohojo/sqm-scripts/blob/master/luci/sqm-cbi.lua#L98
```
Queuing disciplines useable on this system; 
instantiated only after first successful start of SQM. 
You need to start a new GUI session to see updates
```

In reality, the available qdiscs are only evaluated at the router reboot (or when SQM is installed & first run). A manual restart of SQM does not initiate qdisc evaluation, as a separate status directory /var/run/sqm/available_qdiscs/ is used to store the information:
https://github.com/tohojo/sqm-scripts/blob/master/src/run-openwrt.sh#L17
```
[ -d "${SQM_QDISC_STATE_DIR}" ] || ${SQM_LIB_DIR}/update-available-qdiscs
```
User can force the evaluation by deleting the directory /var/run/sqm/available_qdiscs/ , if hhe reads the SQM source code and finds out about that. 

I feel that the evaluation might be good to do also when the user initiates a restart of SQM. However, the qdisc sniffing code is part of the same run.sh that is run also for the hotplug actions, so we should avoid .

I propose that
* the wrong explanation about "new GUI session" is corrected. E.g. the last sentence is either deleted or changed to "After installing new qdiscs, please reboot the router to make them available."
* as a more minor point, please consider making a SQM restart to also force a new evaluation of qdiscs. However, I understand that users rarely do install new qdiscs, so this whole item is a really minor one.

**Comment by tohojo** [comment]
Fixed the help text for now.
