### ISSUE TITLE
How to control win10 updated

### ISSUE THREAD

**Issue by qiuzi** [tohojo/sqm-scripts#28]
Windows10 systems forced circulation system, large file download will affect ADSL bandwidth saturation

**Comment by moeller0** [comment]
Hi quizi,

> On Feb 20, 2016, at 03:15 , qiuzi <notifications@github.com> wrote:
> 
> Windows10 systems forced circulation system, large file download will affect ADSL bandwidth saturation

	As far as I can tell, sqm-scripts should hanfdle that wel out of the box. Do you have any data to show that additional steps seems necessary?
