### ISSUE TITLE
Using insmod vs modprobe

### ISSUE THREAD

**Issue by tohojo** [tohojo/sqm-scripts#3]
What is the reason for using insmod currently? On openwrt modprobe and
insmod seem to be equivalent, and on other systems insmod seems to
expect a filename not a module name. So wouldn't it be more correct to
use modprobe?

**Comment by moeller0** [comment]
On Jul 29, 2015, at 15:25 , Toke H�iland-J�rgensen <notifications@github.com> wrote:

> What is the reason for using insmod currently? On openwrt modprobe and
> insmod seem to be equivalent, and on other systems insmod seems to
> expect a filename not a module name. So wouldn't it be more correct to
> use mod probe?

As far as I know we used ins mod from before I got involved. Maybe older openwrts did not carry mod probe by default? I guess, Dave would know best.
That reminds me we should actually see whether a module exists before trying to load it and give a decent error message if the module is missing, especially for the core modules we require. Maybe the .qos scripts should also check whether the modules actually exist (like htb and hfsc?)?

Best Regards
	Sebastian

**Comment by moeller0** [comment]
modprobe was not available in earlier openwrt systems.

On Wed, Jul 29, 2015 at 3:44 PM, Sebastian Moeller <moeller0@gmx.de> wrote:
>
> On Jul 29, 2015, at 15:25 , Toke Høiland-Jørgensen <notifications@github.com> wrote:
>
>> What is the reason for using insmod currently? On openwrt modprobe and
>> insmod seem to be equivalent, and on other systems insmod seems to
>> expect a filename not a module name. So wouldn't it be more correct to
>> use mod probe?
>
> As far as I know we used ins mod from before I got involved. Maybe older openwrts did not carry mod probe by default? I guess, Dave would know best.
> That reminds me we should actually see whether a module exists before trying to load it and give a decent error message if the module is missing, especially for the core modules we require. Maybe the .qos scripts should also check whether the modules actually exist (like htb and hfsc?)?
>
> Best Regards
>         Sebastian
>
>>
>> —
>> Reply to this email directly or view it on GitHub.
>>
>



-- 
Dave Täht
worldwide bufferbloat report:
http://www.dslreports.com/speedtest/results/bufferbloat
And:
What will it take to vastly improve wifi for everyone?
https://plus.google.com/u/0/explore/makewififast

**Comment by tohojo** [comment]
Right. I'm not sure if it's just my build or if we can generally rely on
it; but maybe just checking for modprobe and falling back to insmod?

Checking for errors and failing gracefully is a separate issue, I think;
currently we don't do that for *anything*...
