### ISSUE TITLE
SQM scripts unused classes

### ISSUE THREAD

**Issue by micmac1** [tohojo/sqm-scripts#47]
Hello all,

in src/simple.qos class 1:10 is created for ingress and egress but never used. The class also never gets a qdisc, e.g. fq_codel, assigned like the other classes, e.g. 1:20. The only exception is on ingress if ["$SQUASH_INGRESS" = "1"]. Is there a reason to add the 1:10 classes anyway? Or can they be removed?

Regards,
Sebastian

**Comment by tohojo** [comment]
No, I think it can be removed (on egress as well).
