### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by moeller0** [tohojo/sqm-scripts#62]
Since the last release in February 2017 we accumulated a few fixes and changes, that should be ready for a wider user group. So how about making a decision on what to do with the bufs that @guidosarducci identified and created fixes for in the current code base and organize a new release?

**Comment by tohojo** [comment]
moeller0 <notifications@github.com> writes:

> Since the last release in February 2017 we accumulated a few fixes and
> changes, that should be ready for a wider user group. So how about
> making a decision on what to do with the bufs that @guidosarducci
> identified and created fixes for in the current code base and organize
> a new release?

If you collect the bug fixes and submit a pull request I am happy to
merge it and cut a new release. I don't have the time to do so myself,
unfortunately...

-Toke

**Comment by moeller0** [comment]
Hi Toke,


> On Jan 26, 2018, at 14:43, Toke Høiland-Jørgensen <notifications@github.com> wrote:
> 
> moeller0 <notifications@github.com> writes:
> 
> > Since the last release in February 2017 we accumulated a few fixes and
> > changes, that should be ready for a wider user group. So how about
> > making a decision on what to do with the bufs that @guidosarducci
> > identified and created fixes for in the current code base and organize
> > a new release?
> 
> If you collect the bug fixes and submit a pull request I am happy to
> merge it and cut a new release. I don't have the time to do so myself,
> unfortunately...

Great, I will see how to do this then. Thanks

Best Regards

**Comment by dtaht** [comment]
+1

**Comment by tohojo** [comment]
Hmm, did actually tag a new release, just never got around to pushing it to
openwrt; have done so now :)
