### ISSUE TITLE
Small Improvements

### ISSUE THREAD

**Issue by negan07** [tohojo/sqm-scripts#67]
1. Tuning for 100+ Mbps wan link connections (FTTC/FTTH).
2. Setting of up/dw rate unit of measurements (Mpbs/Kbps).
3. Automate for Link Layer setting.

**Comment by moeller0** [comment]
> Automate for Link Layer setting.

I would, if I knew how. For ATM/AAL5 this is somewhat straight forward (see [https://github.com/moeller0/ATM_overhead_detector](url)) albeit slow and quite data intensive, but we have nothing for DOCSIS/GPON/pure ethernet/LTE/...
So the issues is twofold first we need to detect the link technology and then we need to empirically deduce the per packet overhead. Both are hard...

**Comment by moeller0** [comment]
> Setting of up/dw rate unit of measurements (Mpbs/Kbps).

I believe this could be handled completely in luci-app-sqm, so should be doable relatively easily. Is that really an important issue though?

**Comment by moeller0** [comment]
> Tuning for 100+ Mbps wan link connections (FTTC/FTTH)

Not exactly sure what you consider to be appropriate tuning for those links?

**Comment by negan07** [comment]
> > Setting of up/dw rate unit of measurements (Mpbs/Kbps).
> 
> I believe this could be handled completely in luci-app-sqm, so should be doable relatively easily. Is that really an important issue though?

I did it easily with a simple conversion after variable assignement creating tho new vars: many fiber connection now supporting 100mb+ and this could simplify settings for people

```
[ -z "UP_RATE_UNIT" ] && UP_RATE_UNIT="Kbps"
[ -z  "DW_RATE_UNIT" } && DW_RATE_UNIT="Kbps" 

# Convert ul/dw rate values from mbps to kbps to mantain compatibility
[ "${UP_RATE_UNIT}" = "Mbps" ] && UPLINK=$(( ${UPLINK} * 1024 )) && UP_RATE_UNIT="Kbps"
[ "${DW_RATE_UNIT}" = "Mbps" ] && DOWNLINK=$(( ${DOWNLINK} * 1024 )) && DW_RATE_UNIT="Kbps"

```
original values remain unchanged

recalculation can be done also on gui (whatever it is) on the fly with the integer part of the value in case of non integer division / 1024

**Comment by tohojo** [comment]
negan07 <notifications@github.com> writes:

> [ "${DW_RATE_UNIT}" = "Mbps" ] && DOWNLINK=$(( ${DOWNLINK} * 1024 ))
> && DW_RATE_UNIT="Kbps"

The conversion factor is 1000, not 1024 for M/Kbps :)

**Comment by moeller0** [comment]
> recalculation can be done also on gui (whatever it is) on the fly with the integer part of the value in case of non integer division / 1024

This is technically not fully correct, networking traditionally uses pure SI-prefixes, so 1000 bits  = 1 Kbit, 1000 Kb = 1 Mb...

**Comment by negan07** [comment]
> > Tuning for 100+ Mbps wan link connections (FTTC/FTTH)
> 
> Not exactly sure what you consider to be appropriate tuning for those links?

the old tests where made with slowest wan links (max 60mbps)
now with 17a & 35b fiber VDSL profiles with vectoring and noise suppressors speed link has increased of a decade: this is the reason

I think this is already in progress with the last testing branch `burst_by_duration` including new quantum & burst treatments so the issue can be into this included

**Comment by negan07** [comment]
> > recalculation can be done also on gui (whatever it is) on the fly with the integer part of the value in case of non integer division / 1024
> 
> This is technically not fully correct, networking traditionally uses pure SI-prefixes, so 1000 bits = 1 Kbit, 1000 Kb = 1 Mb...

Thanks for the notification: this can be easily corrected

**Comment by moeller0** [comment]
Ah, okay, sure the burst size has proven to be sub-optimal for 100Mbps+ links. I had naively assumed though that such users would all use cake anyway (which does its own independent buffer sizing and dooes not care for sqm's burts and quantum).

**Comment by negan07** [comment]
> Ah, okay, sure the burst size has proven to be sub-optimal for 100Mbps+ links. I had naively assumed though that such users would all use cake anyway (which does its own independent buffer sizing and dooes not care for sqm's burts and quantum).

yes but unfortunately not all the machines can handle cake qdisc

all the broadcom vdsl/fttc&ffth router modems comes up with a customized 3.4.11 kernel, too old for cake and not upgradable due to private licenses

also fq_codel was out of it, as it's supported since 3.5 so had to retropatch it to make it usable..

**Comment by moeller0** [comment]
Ah, good to know, so if you can actually test the burst_by_duration branch and report back whether it actually improves shaping performance in the real world, that would help a lot in getting that branch pulled into master. BTW, thanks for reviewing that branch and catching bugs!

**Comment by negan07** [comment]
with latest updates I think this issue can be terminated

the burst/quantum variations can do the job

improvements can be done over the luci GUI settings page

the automate for linklayer is possible at least on my machine because there's a setting value indicating the wan traffic type: `ptm, atm` or `void`: according to this, as a beginner's guide-line oriented only, it's possible to setup different profiles of configuration values for overhead, stab mtu, stab tsize, stab mpu
