### ISSUE TITLE
policing attempt. no policing support in openwrt?

### ISSUE THREAD

**Issue by dtaht** [tohojo/sqm-scripts#68]
in desperation, watching fast.com clobber my link, I wanted to try a two tier system, with cake trying to shape to a 85mbit rate, and then policing slightly below my measured inbound rate (110mbit). 

There doesn't appear to be an act_police module in openwrt packages anymore...

tc qdisc add dev eth0 handle ffff: ingress
tc filter add dev eth0 parent ffff: prio 9 u32 match u2 0 0 police rate 100mbit burst 16k
# prio 10 then sends the redirect to ifb4

RTNETLINK answers: No such file or directory

**Comment by tohojo** [comment]
Not sure how this is an sqm-scripts issue?

**Comment by negan07** [comment]
it's an iproute2 issue: upgrade iproute2 to latest or one of the latest

**Comment by guidosarducci** [comment]
@dtaht  Hi Dave,
You probably already realized this, but the `act_police` module is part of the `kmod-sched` package, which isn't installed by default.  What sort of success did you have with policing, and were there parameters/considerations that needed special care?

I'm considering trying to police for one of my setups in which shaping seems to have little effect on bloat, but does improve after aggressively reducing throughput by ~70%. For reference, it happens to be a 15M/1M Cable plan, where half-duplex speed tests show good latency with SQM, but full-duplex tests can show ~3s latency without extreme ingress shaping. One thing I haven't tried yet are one-way tests however...

Thanks.
