### ISSUE TITLE
Hotplug script problem with ACTION=ifdown and DEVICE="" (i.e. empty)

### ISSUE THREAD

**Issue by bytesizebits** [tohojo/sqm-scripts#69]
See OpenWRT  [FS#1741](https://bugs.openwrt.org/index.php?do=details&task_id=1741) for details and logs.

It appears in OpenWRT-18.06 that hotplug events called on the scripts in /etc/hotplug.d/iface/ with ACTION=ifdown ALWAYS set DEVICE= (no device specified).

When /etc/hotplug.d/iface/11-sqm is executed it has the effect of running:

`/usr/lib/sqm/run.sh stop`

Which results in ALL configured sqm instances defined in /etc/config/sqm being deconfigured.
Hotplug events with ACTION=ifup always set DEVICE to a valid physical interface as expected, and sqm for that device is configured. However, any other interface(s) deconfigured during ifdown are left unconfigured.

The 11-sqm hotplug script in OpenWRT-17.01 ignored ifdown events so this was not an issue.

The OpenWRT wiki on hotplug events imply that DEVICE is always set, hence my bugreport on OpenWRT. A simple workaround I'm using for now is to ignore ifdown hotplug events in 11-sqm.

**Comment by tohojo** [comment]
Huh, yeah, translating an empty DEVICE to a call to sqm stop with no parameters is definitely a bug...

Ah, gotta love shell scripting... :/
