### ISSUE TITLE
sqm with cake , unexpected operator

### ISSUE THREAD

**Issue by yutayu** [tohojo/sqm-scripts#75]
sudo sqm reload eth0
Stopping SQM on eth0
Starting SQM script: layer_cake.qos on eth0, in: 11603 Kbps, out: 810 Kbps
/usr/bin/sqm: 291: [: TRUE: unexpected operator
/usr/bin/sqm: 291: [: TRUE: unexpected operator
layer_cake.qos was started on eth0 successfully

**Comment by tohojo** [comment]
Hmm, what distro are you running on?
