### ISSUE TITLE
Time for a new release (with openwrt freeze for 19.N just around the corner)

### ISSUE THREAD

**Issue by moeller0** [tohojo/sqm-scripts#85]
With all the recent changes I believe we should create a new release from master so that the we can distribute those fixes back to our largest? single user group, users of OpenWrt stable releases?

Alternatively I would like to ask which steps/changes are missing to declare a new release?

**Comment by tohojo** [comment]
Sure, let's cut a new release... I'll get to it, promise! :)

**Comment by moeller0** [comment]
Hi Toke,


> On Jan 21, 2019, at 11:55, Toke Høiland-Jørgensen <notifications@github.com> wrote:
> 
> Closed #85.

	Most excellent, thanks!
