### ISSUE TITLE
systemd compatability

### ISSUE THREAD

**Issue by dtaht** [tohojo/sqm-scripts#87]
https://github.com/magnific0/wondershaper/issues/4 indicates we need to do some work for systemd

**Comment by tohojo** [comment]
We already ship a systemd unit file. Added a few tweaks in
d652e72ebfc9d65c89a453772368bf77fcf1a435 and
0f5d1cd079b1eeca0ff73cb6562b90cdeed3bad3 to make things a tiny bit easier, but
it's really nothing fundamental.

**Comment by tohojo** [comment]
Only other thing I can see we might add for this is better documentation (and
packaging I suppose).
