### ISSUE TITLE
How about adding kibibit choice with kilobit.

### ISSUE THREAD

**Issue by yutayu** [tohojo/sqm-scripts#90]
How ?

**Comment by yutayu** [comment]
kilobit = 1000bit
kibibit = 1024bit

**Comment by tohojo** [comment]
yutayu <notifications@github.com> writes:

> kilobit = 1000bit
> kibibit = 1024bit

TC supports what it does; we just expose that. If you want the other
units, just do the conversion?

**Comment by yutayu** [comment]
Pardon me?

**Comment by tohojo** [comment]
yutayu <notifications@github.com> writes:

> Pardon me?

Why do you need multiple units? You can just convert between them...

**Comment by yutayu** [comment]
I wanted to add parameter in eth0.iface.conf.
What do I do in this case?

**Comment by yutayu** [comment]
For example, 
I sed uplink=795 -> 795k. 
This is not 795kibibit.

**Comment by tohojo** [comment]
yutayu <notifications@github.com> writes:

> For example, 
> I sed uplink=795 -> 795k. 
> This is not 795kibibit.

First off, are you sure your link is really measured in kibibit? This is
not a very common unit.

If you are sure, just calculate the value:

kb = 795*1024/1000 = 814

So you set uplink=814 instead...

**Comment by yutayu** [comment]
> yutayu <notifications@github.com> writes:
> For example, I sed uplink=795 -> 795k. This is not 795kibibit.
> First off, are you sure your link is really measured in kibibit? This is not a very common unit. If you are sure, just calculate the value: kb = 795*1024/1000 = 814 So you set uplink=814 instead...

ok XD
